import { describe, expect, it } from 'vitest';

import {
  getUserSkillTags,
  isAutoGeneratedSlugTags,
  mergeSkillTagsForSave,
  normalizeSkillTag,
  resolveOriginalSkillTagsForSave,
} from './modal-utils';

describe('mergeSkillTagsForSave', () => {
  it('合并原标签与用户标签并去重', () => {
    expect(mergeSkillTagsForSave(['github', 'office'], ['office', 'custom'])).toEqual([
      'github',
      'office',
      'custom',
    ]);
  });

  it('选中已有标签后用户标签差集仍可见', () => {
    const original = ['github'];
    const user = ['design'];
    const saved = mergeSkillTagsForSave(original, user);
    expect(getUserSkillTags({ name: 'demo', tags: saved, original_tags: original })).toEqual([
      'design',
    ]);
  });
});

describe('normalizeSkillTag', () => {
  it('统一小写并去空白', () => {
    expect(normalizeSkillTag('  Design ')).toBe('design');
  });
});

describe('isAutoGeneratedSlugTags', () => {
  it('识别由技能名拆词生成的标签', () => {
    expect(isAutoGeneratedSlugTags('frontend-design', ['frontend', 'design'])).toBe(true);
    expect(isAutoGeneratedSlugTags('frontend-design', ['design', 'frontend'])).toBe(true);
  });

  it('真实原标签或用户标签不误判', () => {
    expect(isAutoGeneratedSlugTags('frontend-design', ['默认'])).toBe(false);
    expect(isAutoGeneratedSlugTags('frontend-design', ['frontend', 'design', '默认'])).toBe(false);
    expect(isAutoGeneratedSlugTags('frontend-design', ['frontend'])).toBe(false);
  });
});

describe('resolveOriginalSkillTagsForSave', () => {
  it('保存时丢弃 slug 拆词伪造的原标签', () => {
    expect(
      resolveOriginalSkillTagsForSave({
        name: 'frontend-design',
        tags: ['frontend', 'design', '默认'],
        original_tags: ['frontend', 'design'],
      }),
    ).toEqual([]);
  });

  it('保留真实原标签', () => {
    expect(
      resolveOriginalSkillTagsForSave({
        name: 'frontend-design',
        tags: ['github', '默认'],
        original_tags: ['github'],
      }),
    ).toEqual(['github']);
  });
});

describe('getUserSkillTags slug 污染清理', () => {
  it('编辑回填时不带入 slug 拆词脏标签', () => {
    expect(
      getUserSkillTags({
        name: 'frontend-design',
        tags: ['frontend', 'design', '默认'],
        original_tags: ['frontend', 'design'],
      }),
    ).toEqual(['默认']);
  });
});
