import type { DUpdateSkill, ISkill } from '@/types/modules';

function isRemoteSourceUrl(sourceUrl?: string): boolean {
  return /^https?:\/\//i.test(sourceUrl || '');
}

export function getExistingSkillTags(skills: ISkill[]): string[] {
  return [...new Set(skills.flatMap((skill) => getUserSkillTags(skill)))].sort((a, b) =>
    a.localeCompare(b),
  );
}

export function inferOriginalSkillTags(
  skill: Pick<ISkill, 'name' | 'tags' | 'original_tags' | 'registry_slug' | 'source_url'>,
): string[] {
  if (Array.isArray(skill.original_tags)) {
    // 历史脏数据：由 slug 拆词写入的 original_tags 不当作原标签
    if (isAutoGeneratedSlugTags(skill.name, skill.original_tags)) {
      return [];
    }
    return skill.original_tags;
  }

  // Legacy imported skills stored source tags directly in tags.
  if (skill.registry_slug || isRemoteSourceUrl(skill.source_url)) {
    const legacyTags = skill.tags || [];
    if (isAutoGeneratedSlugTags(skill.name, legacyTags)) {
      return [];
    }
    return legacyTags;
  }

  return [];
}

export function getUserSkillTags(
  skill: Pick<ISkill, 'name' | 'tags' | 'original_tags' | 'registry_slug' | 'source_url'>,
): string[] {
  const rawOriginalTags = Array.isArray(skill.original_tags) ? skill.original_tags : [];
  const isSlugPolluted = isAutoGeneratedSlugTags(skill.name, rawOriginalTags);
  const slugTagSet = isSlugPolluted
    ? new Set(rawOriginalTags.map(normalizeSkillTag))
    : new Set<string>();
  const originalTags = new Set(inferOriginalSkillTags(skill));
  return (skill.tags || []).filter((tag) => {
    if (originalTags.has(tag)) {
      return false;
    }
    // 历史脏数据：slug 拆词标签即使已并入 tags，也不当作用户标签回填
    if (slugTagSet.has(normalizeSkillTag(tag))) {
      return false;
    }
    return true;
  });
}

export function normalizeSkillTag(raw: string): string {
  return raw.trim().toLowerCase();
}

/**
 * 判断标签是否由技能名 slug 拆词生成（如 frontend-design → frontend, design）。
 * 用于清理历史错误写入的 original_tags，避免编辑保存时再次带入。
 */
export function isAutoGeneratedSlugTags(skillName: string, tags: string[]): boolean {
  const parts = skillName
    .trim()
    .toLowerCase()
    .split(/[-_]/)
    .map((part) => part.trim())
    .filter(Boolean);
  if (parts.length < 2 || tags.length !== parts.length) {
    return false;
  }
  const normalizedTags = tags.map(normalizeSkillTag).filter(Boolean);
  if (normalizedTags.length !== parts.length) {
    return false;
  }
  const sortedParts = [...parts].sort();
  const sortedTags = [...normalizedTags].sort();
  return sortedParts.every((part, index) => part === sortedTags[index]);
}

/** 推断可写入的原标签：丢弃由 slug 拆词伪造的历史脏数据 */
export function resolveOriginalSkillTagsForSave(
  skill: Pick<ISkill, 'name' | 'tags' | 'original_tags' | 'registry_slug' | 'source_url'>,
): string[] {
  return inferOriginalSkillTags(skill);
}

/** 保存时合并原标签与用户标签，保证 tags 为全集且去重 */
export function mergeSkillTagsForSave(originalTags: string[], userTags: string[]): string[] {
  const merged: string[] = [];
  const seen = new Set<string>();
  for (const tag of [...originalTags, ...userTags]) {
    const normalized = normalizeSkillTag(tag);
    if (!normalized || seen.has(normalized)) {
      continue;
    }
    seen.add(normalized);
    merged.push(normalized);
  }
  return merged;
}

/** 按 A-Za-z 字母序排序标签（大小写不敏感，相同字母大写在前） */
export function sortSkillTagsAz(tags: string[]): string[] {
  return [...tags].sort((left, right) =>
    left.localeCompare(right, 'en', { sensitivity: 'accent', caseFirst: 'upper' }),
  );
}

export function normalizeSkillTagList(tags: string[]): string[] {
  const normalizedList: string[] = [];
  const seen = new Set<string>();
  for (const tag of tags) {
    const normalized = normalizeSkillTag(String(tag));
    if (!normalized || seen.has(normalized)) {
      continue;
    }
    seen.add(normalized);
    normalizedList.push(normalized);
  }
  return normalizedList;
}

/** 收集技能上的全部标签并按 A-Za-z 排序 */
export function collectAllSkillTags(skills: Array<Pick<ISkill, 'tags'>>): string[] {
  const tagSet = new Set<string>();
  for (const skill of skills) {
    for (const tag of skill.tags || []) {
      const normalized = normalizeSkillTag(tag);
      if (normalized) {
        tagSet.add(normalized);
      }
    }
  }
  return sortSkillTagsAz([...tagSet]);
}

function hasSameTagList(left: string[] | undefined, right: string[]): boolean {
  const current = left || [];
  if (current.length !== right.length) {
    return false;
  }
  return current.every((item, index) => item === right[index]);
}

/** 从技能的 tags / original_tags 中删除指定标签 */
export function removeTagFromSkillFields(
  skill: Pick<ISkill, 'tags' | 'original_tags'>,
  tag: string,
): DUpdateSkill | null {
  const normalized = normalizeSkillTag(tag);
  if (!normalized) {
    return null;
  }
  const nextTags = (skill.tags || []).filter((item) => normalizeSkillTag(item) !== normalized);
  const nextOriginalTags = (skill.original_tags || []).filter(
    (item) => normalizeSkillTag(item) !== normalized,
  );
  if (
    hasSameTagList(skill.tags, nextTags) &&
    hasSameTagList(skill.original_tags, nextOriginalTags)
  ) {
    return null;
  }
  return {
    tags: nextTags,
    original_tags: nextOriginalTags,
  };
}

/** 将选中标签同步到技能：关联则写入，未关联则移除 */
export function syncSkillTagsAssociation(
  skill: Pick<ISkill, 'tags' | 'original_tags'>,
  selectedTags: string[],
  isAssociated: boolean,
): DUpdateSkill | null {
  const tagsToSync = normalizeSkillTagList(selectedTags);
  if (tagsToSync.length === 0) {
    return null;
  }

  if (isAssociated) {
    const nextTags = mergeSkillTagsForSave(skill.tags || [], tagsToSync);
    if (hasSameTagList(skill.tags, nextTags)) {
      return null;
    }
    return { tags: nextTags };
  }

  const tagSet = new Set(tagsToSync);
  const nextTags = (skill.tags || []).filter((item) => !tagSet.has(normalizeSkillTag(item)));
  const nextOriginalTags = (skill.original_tags || []).filter(
    (item) => !tagSet.has(normalizeSkillTag(item)),
  );
  if (
    hasSameTagList(skill.tags, nextTags) &&
    hasSameTagList(skill.original_tags, nextOriginalTags)
  ) {
    return null;
  }
  return {
    tags: nextTags,
    original_tags: nextOriginalTags,
  };
}

export async function persistRemoveSkillTag(
  tag: string,
  skills: ISkill[],
  updateSkill: (id: string, data: DUpdateSkill) => Promise<unknown>,
): Promise<number> {
  const results = await Promise.allSettled(
    skills.map(async (skill) => {
      const patch = removeTagFromSkillFields(skill, tag);
      if (!patch) {
        return false;
      }
      await updateSkill(skill.id, patch);
      return true;
    }),
  );
  return results.filter((result) => result.status === 'fulfilled' && result.value).length;
}

export async function persistAssociateSkillTags(
  selectedTags: string[],
  associatedSkillIds: string[],
  skills: ISkill[],
  updateSkill: (id: string, data: DUpdateSkill) => Promise<unknown>,
): Promise<number> {
  const associatedIdSet = new Set(associatedSkillIds);
  const results = await Promise.allSettled(
    skills.map(async (skill) => {
      const patch = syncSkillTagsAssociation(skill, selectedTags, associatedIdSet.has(skill.id));
      if (!patch) {
        return false;
      }
      await updateSkill(skill.id, patch);
      return true;
    }),
  );
  return results.filter((result) => result.status === 'fulfilled' && result.value).length;
}
