import type { ISkill } from '@/types/modules';

function isRemoteSourceUrl(sourceUrl?: string): boolean {
  return /^https?:\/\//i.test(sourceUrl || '');
}

export function getExistingSkillTags(skills: ISkill[]): string[] {
  return [...new Set(skills.flatMap((skill) => getUserSkillTags(skill)))].sort((a, b) =>
    a.localeCompare(b),
  );
}

export function inferOriginalSkillTags(
  skill: Pick<ISkill, 'name' | 'tags' | 'original_tags' | 'registry_slug' | 'source_url'>,
): string[] {
  if (Array.isArray(skill.original_tags)) {
    // 历史脏数据：由 slug 拆词写入的 original_tags 不当作原标签
    if (isAutoGeneratedSlugTags(skill.name, skill.original_tags)) {
      return [];
    }
    return skill.original_tags;
  }

  // Legacy imported skills stored source tags directly in tags.
  if (skill.registry_slug || isRemoteSourceUrl(skill.source_url)) {
    const legacyTags = skill.tags || [];
    if (isAutoGeneratedSlugTags(skill.name, legacyTags)) {
      return [];
    }
    return legacyTags;
  }

  return [];
}

export function getUserSkillTags(
  skill: Pick<ISkill, 'name' | 'tags' | 'original_tags' | 'registry_slug' | 'source_url'>,
): string[] {
  const rawOriginalTags = Array.isArray(skill.original_tags) ? skill.original_tags : [];
  const isSlugPolluted = isAutoGeneratedSlugTags(skill.name, rawOriginalTags);
  const slugTagSet = isSlugPolluted
    ? new Set(rawOriginalTags.map(normalizeSkillTag))
    : new Set<string>();
  const originalTags = new Set(inferOriginalSkillTags(skill));
  return (skill.tags || []).filter((tag) => {
    if (originalTags.has(tag)) {
      return false;
    }
    // 历史脏数据：slug 拆词标签即使已并入 tags，也不当作用户标签回填
    if (slugTagSet.has(normalizeSkillTag(tag))) {
      return false;
    }
    return true;
  });
}

export function normalizeSkillTag(raw: string): string {
  return raw.trim().toLowerCase();
}

/**
 * 判断标签是否由技能名 slug 拆词生成（如 frontend-design → frontend, design）。
 * 用于清理历史错误写入的 original_tags，避免编辑保存时再次带入。
 */
export function isAutoGeneratedSlugTags(skillName: string, tags: string[]): boolean {
  const parts = skillName
    .trim()
    .toLowerCase()
    .split(/[-_]/)
    .map((part) => part.trim())
    .filter(Boolean);
  if (parts.length < 2 || tags.length !== parts.length) {
    return false;
  }
  const normalizedTags = tags.map(normalizeSkillTag).filter(Boolean);
  if (normalizedTags.length !== parts.length) {
    return false;
  }
  const sortedParts = [...parts].sort();
  const sortedTags = [...normalizedTags].sort();
  return sortedParts.every((part, index) => part === sortedTags[index]);
}

/** 推断可写入的原标签：丢弃由 slug 拆词伪造的历史脏数据 */
export function resolveOriginalSkillTagsForSave(
  skill: Pick<ISkill, 'name' | 'tags' | 'original_tags' | 'registry_slug' | 'source_url'>,
): string[] {
  return inferOriginalSkillTags(skill);
}

/** 保存时合并原标签与用户标签，保证 tags 为全集且去重 */
export function mergeSkillTagsForSave(originalTags: string[], userTags: string[]): string[] {
  const merged: string[] = [];
  const seen = new Set<string>();
  for (const tag of [...originalTags, ...userTags]) {
    const normalized = normalizeSkillTag(tag);
    if (!normalized || seen.has(normalized)) {
      continue;
    }
    seen.add(normalized);
    merged.push(normalized);
  }
  return merged;
}

interface ISkillTagActionsParams {
  tags: string[];
  tagInput: string;
  setTags: (tags: string[]) => void;
  setTagInput: (value: string) => void;
}

/** 技能表单标签增删与回车添加 */
export function buildSkillTagActions({
  tags,
  tagInput,
  setTags,
  setTagInput,
}: ISkillTagActionsParams) {
  const handleAddTag = () => {
    const normalized = normalizeSkillTag(tagInput);
    if (normalized && !tags.includes(normalized)) {
      setTags([...tags, normalized]);
    }
    setTagInput('');
  };

  const handleRemoveTag = (tag: string) => {
    setTags(tags.filter((item) => item !== tag));
  };

  const handleTagKeyDown = (event: React.KeyboardEvent) => {
    if (event.key === 'Enter') {
      event.preventDefault();
      handleAddTag();
    }
  };

  const handleAddExistingTag = (tag: string) => {
    const normalized = normalizeSkillTag(tag);
    if (normalized && !tags.includes(normalized)) {
      setTags([...tags, normalized]);
    }
  };

  return {
    handleAddTag,
    handleRemoveTag,
    handleTagKeyDown,
    handleAddExistingTag,
  };
}
