import {
  ArrowRightLeft,
  Boxes,
  Brain,
  CalendarRange,
  ChartArea,
  Circle,
  Clock,
  CodeXml,
  Columns3,
  Database,
  FileCheck,
  FolderTree,
  GitBranch,
  GitCommitHorizontal,
  LayoutGrid,
  LayoutTemplate,
  LineChart,
  Map,
  Network,
  Package,
  PieChart,
  Route,
  Target,
  Workflow,
  Zap,
  type LucideIcon,
} from 'lucide-react';

const CHART_MENU_ICON_MAP: Record<string, LucideIcon> = {
  flow: GitBranch,
  flowLR: GitBranch,
  sequence: ArrowRightLeft,
  class: Boxes,
  state: Circle,
  erDiagram: Database,
  journey: Route,
  gantt: CalendarRange,
  pie: PieChart,
  quadrant: LayoutGrid,
  requirement: FileCheck,
  gitgraph: GitCommitHorizontal,
  mindmap: Brain,
  timeline: Clock,
  sankey: Workflow,
  xychart: LineChart,
  block: LayoutTemplate,
  packet: Package,
  kanban: Columns3,
  architecture: Network,
  radar: Target,
  eventModeling: Zap,
  treemap: FolderTree,
  venn: Circle,
  ishikawa: Workflow,
  wardley: Map,
  cynefin: LayoutGrid,
  treeView: FolderTree,
  zenuml: ArrowRightLeft,
  plantumlSequence: ArrowRightLeft,
  plantumlUseCase: Target,
  plantumlClass: Boxes,
  plantumlActivity: Workflow,
  plantumlComponent: Network,
  plantumlState: Circle,
  plantumlObject: Boxes,
  plantumlDeployment: Network,
  plantumlTiming: Clock,
  plantumlNetwork: Network,
  plantumlSalt: LayoutTemplate,
  plantumlArchimate: Network,
  plantumlGantt: CalendarRange,
  plantumlMindmap: Brain,
  plantumlWbs: FolderTree,
  plantumlJson: CodeXml,
  plantumlYaml: CodeXml,
  plantumlErd: Database,
  plantumlWireframe: LayoutTemplate,
  plantumlDefault: CodeXml,
};

export function getChartMenuIcon(direct: string): LucideIcon {
  return CHART_MENU_ICON_MAP[direct] ?? ChartArea;
}
